[build]
cmd = "go run main.go"
bin = "tmp/main"

[log]
level = "info"

[watch]
extensions = ["go", "html", "css", "js"]
full_build_dir = ["./"]

[custom]
tailwind = "tailwindcss -i ./static/css/tailwind.css -o ./static/css/output.css --watch"
