name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.0

    - name: Build Go binary
      run: go build -o main ./cmd/

    - name: Generate static files
      run: ./main

    - name: Copy static files to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.CD_HOST }}
        username: ubuntu
        key: ${{ secrets.CD_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/hintermann.ro/dist/"
